//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeRegistration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int Id { get; set; }
        public int CourseID { get; set; }
        public int FacultyID { get; set; }
        public string Day { get; set; }
        public string Time { get; set; }
        public string Semester { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
